### ISSUE TITLE
View seems to always use "fit"

### ISSUE THREAD

**Issue by stpaultim** [albanycomputers/views_grid_repeat#2]
I am testing the module and in general it seems to work, in that it provides a mobile friendly grid option for views. 

However, I can't get it to behave any differently between fit or fill. Both seem to do the same thing. 

The help text is a bit confusing, because it says 

```
Choose either Fit or Fill. Fit will expand the column to fit the content to the available space. 
Fill will have as many columns as needed but will keep the minimum and maximum size, 
If there is not enough columns to fit the width, you will have a visible space on the left.
```
But, I am only asked for a column width. I don't know where minimum and maximum come from?

I think that the problem is that regardless of "fit" or "fill" this is the CSS:

`grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));`

So, with further testing - I think the the choice between fit and fill is not working. The view always uses fit regardless of the settings. 

This is my settings for view:

![image](https://user-images.githubusercontent.com/3144571/141664907-5b8c102a-158b-4dfa-a54a-84a9debbed5a.png)

It looks exactly like this for both options (Chrome tells me that each grid box is 279px wide). 

![image](https://user-images.githubusercontent.com/3144571/141664936-def81549-da3a-4b83-bf2c-1129128710f2.png)

**Comment by albanycomputers** [comment]
Fixed...

There is a very subtle difference between the two...  FILL only works when there are fewer items horizontally than fit the space, so if you have three items and you could FILL four, then the FILL will leave a bigger gap at the left... whereas with FIT it increases the spacing take up the available space.

**Comment by albanycomputers** [comment]
FILL when you have more items than fits the horizontal.
![image](https://user-images.githubusercontent.com/1705388/141678471-7b9ff926-4fe6-4cc2-a9d8-cf5ca5ba63e4.png)


FILL when the number of items does not fill the horizontal space available.
![image](https://user-images.githubusercontent.com/1705388/141678565-ec09c960-22cc-4ae2-922f-1c4566a78723.png)

FIT when the number of items does not fill the horizontal space available.
![image](https://user-images.githubusercontent.com/1705388/141678574-d0f78a73-9d7e-41d6-b094-2ec26d97c496.png)
